### ISSUE TITLE
Providing password

### ISSUE THREAD

**Issue by russellhoff** [OpenTransitTools/gtfsdb#19]
I've tried to upload a GTFS to my Amazon AWS RDS Instance (PostgreSQL). Unfortunately, an error was thrown, as no password was supplied in the command line. I've looking for any parameter to provide the password, but there isn't. Is there any chance this could be resolved? Thank you so much!

**Comment by mwferris** [comment]
Hi @russellhoff, to get around this you should configure your pg_hba.conf file to TRUST. This isn't a gtfsdb issue.

For more information see https://www.postgresql.org/docs/9.3/static/auth-pg-hba-conf.html
