### ISSUE TITLE
Building problem: psycopg2 during buildout install prod postgresql

### ISSUE THREAD

**Issue by KAMI911** [OpenTransitTools/gtfsdb#26]
buildout install prod postgresql
Develop: '/common/git/gtfsdb/.'
/usr/local/lib/pypy2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.1.6dev' to '0.1.6.dev0'
  normalized_version,
Updating prod.
Installing postgresql.
Getting distribution for 'psycopg2>=2.4.2'.
psycopg/pqpath.c: In function ‘pq_read_replication_message’:
psycopg/pqpath.c:1673:5: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
     gettimeofday(&repl->last_io, NULL);
     ^
psycopg/pqpath.c: In function ‘pq_copy_both’:
psycopg/pqpath.c:1820:13: warning: implicit declaration of function ‘timeradd’ [-Wimplicit-function-declaration]
             timeradd(&repl->last_io, &keep_intr, &ping_time);
             ^
psycopg/pqpath.c:1821:13: warning: implicit declaration of function ‘timersub’ [-Wimplicit-function-declaration]
             timersub(&ping_time, &curr_time, &timeout);
             ^
psycopg/libpq_support.c: In function ‘feGetCurrentTimestamp’:
psycopg/libpq_support.c:55:5: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
     gettimeofday(&tp, NULL);
     ^
psycopg/connection_int.c: In function ‘conn_get_python_codec’:
psycopg/connection_int.c:479:21: warning: implicit declaration of function ‘PyCodec_Encoder’ [-Wimplicit-function-declaration]
     if (!(enc_tmp = PyCodec_Encoder(Bytes_AS_STRING(encname)))) { goto exit; }
                     ^
psycopg/connection_int.c:479:19: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     if (!(enc_tmp = PyCodec_Encoder(Bytes_AS_STRING(encname)))) { goto exit; }
                   ^
psycopg/connection_int.c:480:21: warning: implicit declaration of function ‘PyCodec_Decoder’ [-Wimplicit-function-declaration]
     if (!(dec_tmp = PyCodec_Decoder(Bytes_AS_STRING(encname)))) { goto exit; }
                     ^
psycopg/connection_int.c:480:19: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     if (!(dec_tmp = PyCodec_Decoder(Bytes_AS_STRING(encname)))) { goto exit; }
                   ^
psycopg/replication_cursor_type.c: In function ‘psyco_repl_curs_start_replication_expert’:
psycopg/replication_cursor_type.c:77:9: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
         gettimeofday(&self->last_io, NULL);
         ^
psycopg/adapter_datetime.c: In function ‘_pydatetime_string_delta’:
psycopg/adapter_datetime.c:103:16: error: ‘PyDateTime_Delta {aka struct <anonymous>}’ has no member named ‘microseconds’
     int a = obj->microseconds;
                ^
psycopg/adapter_datetime.c:112:32: error: ‘PyDateTime_Delta {aka struct <anonymous>}’ has no member named ‘days’
                             obj->days, obj->seconds, buffer);
                                ^
psycopg/adapter_datetime.c:112:43: error: ‘PyDateTime_Delta {aka struct <anonymous>}’ has no member named ‘seconds’
                             obj->days, obj->seconds, buffer);
                                           ^
error: Setup script exited with error: command 'cc' failed with exit status 1
An error occurred when trying to install /tmp/tmpm_VB_Lget_dist/psycopg2-2.7.3.2.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing postgresql.
  Getting distribution for 'psycopg2>=2.4.2'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/usr/local/lib/pypy2.7/dist-packages/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/usr/local/lib/pypy2.7/dist-packages/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/common/git/gtfsdb/eggs/zc.recipe.egg-2.0.4-py2.7.egg/zc/recipe/egg/egg.py", line 193, in install
    reqs, ws = self.working_set()
  File "/common/git/gtfsdb/eggs/zc.recipe.egg-2.0.4-py2.7.egg/zc/recipe/egg/egg.py", line 82, in working_set
    allow_hosts=self.allow_hosts,
  File "/common/git/gtfsdb/eggs/zc.recipe.egg-2.0.4-py2.7.egg/zc/recipe/egg/egg.py", line 135, in _working_set
    allow_hosts=allow_hosts)
  File "/usr/local/lib/pypy2.7/dist-packages/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/usr/local/lib/pypy2.7/dist-packages/zc/buildout/easy_install.py", line 714, in install
    for dist in self._get_dist(req, ws):
  File "/usr/local/lib/pypy2.7/dist-packages/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/usr/local/lib/pypy2.7/dist-packages/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: expected length 1, got 0

**Comment by fpurcell** [comment]
This looks more like an error with psycopg, than gtfsdb.  FWIW, on my machine (Mac w/ pg 9.4), "buildout install prod postgresql" works and does compile the library.
