### ISSUE TITLE
RAM usage loading TriMet GTFS approaches 5 GB

### ISSUE THREAD

**Issue by znmeb** [OpenTransitTools/gtfsdb#38]
I'm building some tools to run `gtfsdb` and `gtfsrdb` automatically "in the cloud". The project is at <https://github.com/znmeb/gtfs-collector>; comments, etc. greatly appreciated. I have the basics running on Digital Ocean, but it turns out that a late stage of the database insertion process peaks around 5 GB, thus requiring an 8 GB droplet!

So I've dropped back to running `gtfsdb` on a workstation and creating a `pg_dump` backup, which I'll restore before collecting real-time data. But it would be nice if there was some way to limit the RAM usage of `gtfsdb` to something less expensive.

P.S.: I'm using <https://github.com/CUTR-at-USF/gtfsrdb> for the real-time collection. That seems to be working in a 1 GB droplet. Is there any reason I should or should not switch to <https://github.com/OpenTransitTools/gtfsdb_realtime>? I don't have any hard deadlines on this and I have plenty of operational things to do either way.

**Comment by fpurcell** [comment]
p.s., about gtfsrdb vs. gtfsdb_realtime?  

Matt's gtfsrdb project served me well. And if it works for you, there's probably no benefit to moving to gtfsdb_realtime ... they both load a database with a gtfs rt feed. 

I created gtfsdb_realtime for 3 reasons:
 - I wanted to learn more about gtfs-rt
 - I had a bunch of query logic in another project, which didn't have a good home until gtfsdb_realtime
 - I've got it on my todo list to link together the scheduled and real-time data (e.g., link real-time locations to the route a vehicle is serving, visually compare where the vehicle is to what the schedule says should be, etc...) ... so more query logic.  

Eventually I'm probably going to add something like materialized views to link gtfs and gtfs-rt data together, etc...

**Comment by znmeb** [comment]
Thanks! I'm also looking at the R libraries for GTFS in particular and urban GIS in general, since I'm an R programmer. I've run into plenty of RAM issues with those too; the "tidyverse" keeps a lot of intermediate results around if you have long chains of pipes. So I'm leaning heavily on PostGIS for this.
