### ISSUE TITLE
ReadMe Out of Date

### ISSUE THREAD

**Issue by adampitchie** [OpenTransitTools/gtfsdb#4]
I just tried doing a gtfsdb-load, and there is no longer a bin folder that is created after buildout. Can you update the readme to reflect the appropriate load instructions in its current form?

Thanks!

Adam

**Comment by fpurcell** [comment]
Hey Adam,

That's not the behavior I'm seeing:

> rm -rf gtfsdb
> git clone git@github.com:OpenTransitTools/gtfsdb.git
> cd gtfsdb
> buildout install prod
Creating directory '/gtfsdb/bin'.
Develop: '/gtfsdb/.'
Uninstalling prod.
Installing prod.
Generated script 'gtfsdb/bin/connect-tester'.
Generated script 'gtfsdb/bin/gtfsdb-load'.
Generated script 'gtfsdb/bin/rs-test'.
Generated interpreter 'gtfsdb/bin/python'.
> bin/gtfsdb-load --database_url sqlite:///gtfs.db http://developer.trimet.org/schedule/gtfs.zip
15:52:33,807 DEBUG [/gtfsdb/gtfsdb/model/db.py] create table: route_type
....
15:52:44,256 DEBUG [gtfsdb.model.gtfs] GTFS.load: http://developer.trimet.org/schedule/gtfs.zip
15:52:45,128 DEBUG [gtfsdb.model.route] RouteType.load (0 seconds)
15:52:45,140 DEBUG [gtfsdb.model.route] RouteFilter.load (0 seconds)
15:52:45,169 DEBUG [gtfsdb.model.feed_info] FeedInfo.load (0 seconds)
15:52:45,178 DEBUG [gtfsdb.model.agency] Agency.load (0 seconds)
....

I've done the following on both a mac (just now), on a centos linux machine, and via both cygwin cmdline and powershell on a pc (recent past).

Hope this helps,
Frank
