### ISSUE TITLE
Database ingest times

### ISSUE THREAD

**Issue by mattcaruso** [OpenTransitTools/gtfsdb#63]
I'm currently building a database from the NJ Transit bus GTFS files. The data is about 200MB uncompressed. It's taking 3+ days to build the database. Is that expected? Or do you think this could be an issue with my Postgres host? 

I've searched around the repo's discussions to see if expected processing times is mentioned anywhere and haven't had any luck.

**Comment by fpurcell** [comment]
That seems a bit strange, Matt.  I load TriMet's data all the time, and the stop_times.txt file itself is ~150MB.  I'll try to find some time to take a peak at that NJT feed.

**Comment by fpurcell** [comment]
[njt_route.json](https://github.com/OpenTransitTools/gtfsdb/files/15232638/njt_route.json)

**Comment by fpurcell** [comment]
<img width="1108" alt="Screenshot 2024-05-07 at 1 21 24 AM" src="https://github.com/OpenTransitTools/gtfsdb/assets/64323/f73ace6b-385a-4536-b330-c0a5d336a195">
